# Generated by Django 4.1.7 on 2023-03-30 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="techskills",
            new_name="tech_skills",
        ),
    ]
